### ISSUE TITLE
[FE] 컴포넌트 생성

### ISSUE THREAD

**Issue by jooYeonIya** [bbman9900/Ducktion#1]
## Description

- 프로젝트에서 사용할 컴포넌트를 생성합니다.

## Tasks

- [x] Labels 컴포넌트: 고도체(타이틀, 서브타이틀), 프리텐다드체(타이틀, 서브타이틀, 텍스트, 캡션)
- [x] IconPlusLabel 컴포넌트
- [x] RectangleButton 컴포넌트
- [x] RoundButton 컴포넌트 + 선택되었을 때 변경 사항 반영
- [x] TextField 컴포넌트 : 플레이스홀더 있음
- [x] 비드 템플릿 컴포넌트
- [x] 출품 상품 카드: 상품명 + 가격
- [x] 출품 상품 카드: 입찰 건수, 종료일
- [x] 출품 상품 카드: only 상품명
- [x] 출품 상품 카드: 출품 일시

**Comment by jooYeonIya** [comment]
아이템 카드는 종류별로 만들려고 했으나 하나로 만들었음
develop에서 필요없는 부분, 수정 사항(이슈 2, 이슈 6) 같이 병합
