### ISSUE TITLE
[FE] 커뮤니티 개설 요청 페이지 작성 

### ISSUE THREAD

**Issue by glennman1** [bbman9900/Ducktion#2]
## Description

- 커뮤니티 개설 요청 페이지 작성

## Tasks

- [x]  타이틀작성 기능 추가
- [x]  내용작성 기능 추가
- [x]  확인 취소 버튼 구현

**Comment by glennman1** [comment]
tsx -> jsx
