### ISSUE TITLE
[FE] 커뮤니티 목록 보기 페이지 구현

### ISSUE THREAD

**Issue by bbman9900** [bbman9900/Ducktion#3]
## Description

- 커뮤니티 목록 보기 페이지를 구현합니다.

## Tasks

- [x]  가나다순, 알파벳순, MY 탭 구현
- [x]  전체, 초성 또는 알파벳 탭 구현
- [x]  커뮤니티 목록 리스트 구현
- [x] 커뮤니티 개설 요청 버튼 구현

**Comment by bbman9900** [comment]
전체 보기 로직 수정, CSS 작업 필요
